### ISSUE TITLE
Add a "back button" method

### ISSUE THREAD

**Issue by DeflateAwning** [MechanicalSoup/MechanicalSoup#419] opened 2023-05-08 04:46 UTC
I want to be able to call `browser.back()` to navigate back one page, similar to how a browser would. 

## Why I want it
In the absence of a solution to #418, this method would allow for solving that same problem more elegantly.

**Comment by hemberger** [comment] 2023-05-08 04:49
Thanks for the feature request! However, I'm going to close this as a duplicate of #127, which already has a lengthy discussion on this topic.

**Closed by hemberger** 2023-05-08 04:49 UTC
