### ISSUE TITLE
Set up LGTM and fix warnings

### ISSUE THREAD

**Issue by moy** [MechanicalSoup/MechanicalSoup#202] opened 2018-03-19 13:41 UTC
LGTM.com finds one issue in our code, and it seems legitimate to me (although I'm guilty for introducing it):

https://lgtm.com/projects/g/hickford/MechanicalSoup/

We should fix this, and configure lgtm so that it checks pull-requests.

**Comment by hemberger** [comment] 2018-03-19 19:13
I believe I've now enabled the pull request integration for LGTM.

How would you like to resolve this alert? I see two possibilities:
1. Remove the `Browser.launch_browser` override
2. Remove the `soup` argument from `StatefulBrowser.launch_browser`.

I think the 2nd option is probably the most backwards compatible, and should result in the exact same functionality that we have now.

**Comment by moy** [comment] 2018-03-19 19:38
Actually, looking a bit closer, I don't think the warning is legitimate:

* The method override does follow Liskov's Substitution Principle: a call to `browser.launch_browser` still works with StatefulBrowser. The user *has* to provide the `soup` argument when calling a method on the base class, and *may* still provide it (but doesn't have to anymore) for the derived class.

* All calls to `x.launch_browser()` without arguments are done as `self.launch_browser()` where it's clear that `self` is a `StatefulBrowser`, not a `Browser`.

Am I missing something?

**Comment by hemberger** [comment] 2018-03-20 14:05
[This SO answer](https://stackoverflow.com/a/6034715/8834658) suggests that LSP is violated. I assume this is formally because you can't verify that the method arguments are contravariant if the signature is different. I don't understand the comment about "external code" though.

If we think about this in a more strict language, like c++, what is currently implemented by `launch_browser` works correctly (as it does in python):

```c++
#include <iostream>
using namespace std;

class A {
    public:
        void print(int x) { cout << "x=" << x; }
};

class B: public A {
    public:
        void print(int x, int y=10) { cout << "x,y=" << x << "," << y; }
};

int main() {
    B b = B();
    b.print(20);
    
    return 0;
}
```
This outputs `x,y=20,10` as expected. However, if we make `A::print` pure virtual, or if we mark `B::print` with the `override` keyword, then we get a compiler error since it's not actually overriding `A::print`. Nevertheless, we are _hiding_ `A::print` since there is no way to access it without casting to the base class.

Does this mean that LSP is violated when base class methods are hidden? A quick google search seems to indicate that the answer is "yes", but the explanations seem a bit more subtle (e.g. "LSP, but not at the syntactical level"...).

**Comment by moy** [comment] 2018-03-20 22:30
> This SO answer suggests that LSP is violated.

This is not the same case. The answer you're pointing to shows a case where the derived class _forces_ several arguments when the base class' method took none. The one we're dealing with is:

* Base class forces one argument
* Derived class' method also accepts one argument, but allows no argument too. It's strictly more permissive.

The analogy with C++ is limited, since default argument value is resolved statically in C++ while Python resolves it dynamically. The notion of _hiding_ method does not really have an equivalent in Python: Python just grabs the first method it finds with the name, all dynamically.

For example:

<pre>
class Base():
    def foo(self, x):
        print(x)

class Derived():
    def foo(self, x=42):
        print(x)

d = Derived()
d.foo(10)
d.foo()  # outputs 42
b = Base()
b.foo(10)
b.foo()  # Forbidden
</pre>

**Comment by hemberger** [comment] 2018-03-20 22:37
I've deactivated pull request integrations for LGTM. I'll close this issue in a few days if there's no further discussion.

**Comment by moy** [comment] 2018-03-21 15:41
> I've deactivated pull request integrations for LGTM.

The fact that the only current warning is a false-positive doesn't mean the tool isn't interesting.

Actually, I like using MechanicalSoup as a real-life but small-sized test-case for this kind of tools, so I'd be in favor of re-enabling the pull-request integration. OTOH the expected actual benefit is indeed quite small.

**Comment by hemberger** [comment] 2018-03-21 19:31
I had assumed (perhaps incorrectly) that having the PR hook enabled without addressing the error would result in a ![image](https://user-images.githubusercontent.com/846186/37732829-73f0845c-2d03-11e8-89da-fe7390b11d2f.png) for every PR, which would certainly be counterproductive. I have no objection to re-enabling if it doesn't do that.

**Comment by moy** [comment] 2018-03-21 19:39
I'm assuming that it would point out only warnings that appear in the diff, but I haven't tested. It's also possible to add in-code annotations to disable warnings, but we may not want to pollute the code if there's no real benefit.

**Comment by hemberger** [comment] 2018-06-06 21:50
Just checking in on this again, I see that there are no LGTM alerts for MechanicalSoup, so perhaps they fixed whatever issue was causing the warning we were discussing earlier (and I regret that I never copied the text of the warning here for reference!).

I've re-enabled the PR checking, and I'll close this ticket once I submit a PR to include the LGTM badge somewhere.

**Comment by samlanning** [comment] 2018-06-08 04:52
Hey there, LGTM staff here.

I can confirm that we won't show a red ![](https://user-images.githubusercontent.com/846186/37732829-73f0845c-2d03-11e8-89da-fe7390b11d2f.png) for every PR submitted if there are existing alerts in a PR, that doesn't sound useful to me.

We instead calculate what alerts a particular PR would have introduced, and then post a comment with the details if there would indeed be changes. And even then, if alerts are introduced, we don't fail the PR. Custom failure conditions are something we plan to add eventually however.

**Closed** 2018-06-08 16:10 UTC

**Comment by hemberger** [comment] 2018-06-08 16:12
@samlanning Thanks for the confirmation! I'm looking forward to seeing what we learn by using LGTM!
