### ISSUE TITLE
submit form without explicit <input type="submit">

### ISSUE THREAD

**Issue by ZhouXing19** [MechanicalSoup/MechanicalSoup#329] opened 2020-05-26 16:04 UTC
I am trying to submit login form [here ](https://seekingalpha.com/account/login), but the submit option in this page is not `<input type="submit">`, but

```
 <div class="register_button" onclick="submit_orthodox_login_form();">
        <span class="l"></span>
        <input class="c" type="button" value="Sign in">
        <span class="r"></span>
      </div>
```

I followed the previous steps as follows:

```
br = mechanicalsoup.StatefulBrowser(
    soup_config={'features': 'lxml'},
    raise_on_404=True,
    user_agent='MyBot/0.1: mysite.example.com/bot_info',
)

br.open("https://seekingalpha.com/account/login")
br.select_form('#orthodox_login')


br["login"] = args.username
br["password"] = args.password
resp = br.submit_selected()
```

But in vain.

**Comment by moy** [comment] 2020-05-26 16:30
this `onclick=...();` is a piece of JavaScript. MechanicalSoup can't execute JavaScript code, and won't help here. See https://mechanicalsoup.readthedocs.io/en/stable/faq.html#form-submission-has-no-effect-or-fails.

**Comment by ism** [comment] 2020-06-05 03:52
This code worked for me

```
    br = mechanicalsoup.StatefulBrowser(
        soup_config={'features': 'lxml'},
        raise_on_404=True,
        user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/77.0',
    )

    br.open('https://seekingalpha.com/account/login')
    br.select_form('#orthodox_login')

    br['user[email]'] = args.username
    br['user[password]'] = args.password
    br['user[url_source]'] = 'https://seekingalpha.com/account/login'
    resp = br.submit_selected()

```

**Comment by moy** [comment] 2020-06-05 08:41
Thanks. I'm assuming the problem is solved and closing the issue. Please re-open if needed.

**Closed by moy** 2020-06-05 08:41 UTC
